# MDSC-102 Assignment

1. How to import pandas and check the version?

In [2]:
import pandas as pd 
import numpy as np

In [1]:
print(pd.__version__)

1.4.3


2. How to create a series from a list, numpy array and dict?

In [2]:
# Input
mylist = list('abcedfghijklmnopqrstuvwxyz') # list of strings
myarr = np.arange(26) # numpy array from 0 to 25
mydict = dict(zip(mylist, myarr)) # list and array are joined at corresponding indices in dictionary

In [4]:
s1 = pd.Series(mylist)
s2 = pd.Series(myarr)
s3 = pd.Series(mydict)
print(s3)

a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int32


3. How to convert the index of a series into a column of a dataframe?


In [5]:
df = s3.to_frame().reset_index()
print(df)

   index   0
0      a   0
1      b   1
2      c   2
3      e   3
4      d   4
5      f   5
6      g   6
7      h   7
8      i   8
9      j   9
10     k  10
11     l  11
12     m  12
13     n  13
14     o  14
15     p  15
16     q  16
17     r  17
18     s  18
19     t  19
20     u  20
21     v  21
22     w  22
23     x  23
24     y  24
25     z  25


4. How to get the minimum, 25th percentile, median, 75th, and max of a numeric series?


In [16]:
# Input
state = np.random.RandomState(100) #pseudo-random number generator
ser = pd.Series(state.normal(10, 5, 25)) # Drawing random samples from a normal (Gaussian) distribution.

In [17]:
np.percentile(ser, q=[0, 25, 50, 75, 100])


array([ 1.25117263,  7.70986507, 10.92259345, 13.36360403, 18.0949083 ])

5. How to convert a numpy array to a dataframe of given shape? (L1)


In [19]:
#Input

ser = pd.Series(np.random.randint(1, 10, 35)) # 35 sample random no. from 1 to 9  

In [22]:
df = pd.DataFrame(ser.values.reshape(5,7))
df

0  1  2  3  4  5  6
0  2  6  6  9  9  3  6
1  7  8  2  1  2  3  2
2  1  3  1  3  5  6  2
3  7  8  2  9  7  6  1
4  3  8  5  7  5  8  9

6. How to extract items at given positions from a series

In [27]:
# Input

ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

In [29]:
ser.take(pos) # returns elements at positions passed as parameter

0     a
4     e
8     i
14    o
20    u
dtype: object

7. How to compute the mean squared error on a truth and predicted series?


In [33]:
# Input

truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

In [35]:
np.mean((truth-pred)**2) # Average of square of differences(errors) between truth and pred values

0.3058190237283496

8. How to convert the first character of each element in a series to uppercase?

In [38]:
# Input
ser = pd.Series(['how', 'to', 'do', 'this?'])


In [40]:
ser.map(lambda x: x.title()) # maps values of ser according to the function title, which converts to uppercase


0      How
1       To
2       Do
3    This?
dtype: object

9. How to calculate the number of characters in each word in a series?


In [41]:
# Input
ser = pd.Series(['how', 'to', 'do', 'this?'])

In [43]:
ser.map(lambda x: len(x)) # maps values of ser to the length of each value(string)

0    3
1    2
2    2
3    5
dtype: int64

10. How to compute difference of differences between consecutive numbers of a series?


In [44]:
# Input
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

In [47]:
ser.diff().tolist() # Find discrete difference of elements in given list .

[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]

In [50]:
ser.diff().diff().tolist() # Find discrete difference of difference of elements in given list.

[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]

11. How to convert a series of date-strings to a timeseries?


In [51]:
# Input
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

In [53]:
from dateutil.parser import parse
ser.map(lambda x: parse(x)) #  a generic date/time string parser which is able to parse most formats to represent date and/or time.

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

12. How to convert year-month string to dates corresponding to the 4th day of the month?


In [54]:
# Input
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])

In [55]:
ser.map(lambda x: parse('04 ' + x)) # Particular string is parsed and 04 string is added as date

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]

13. How to compute the euclidean distance between two series?


In [56]:
# Input
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

In [57]:
sum((p-q)**2)**.5

18.16590212458495

14. How to create a TimeSeries starting ‘2000-01-01’ and 10 weekends (saturdays) after that having random numbers as values?


In [58]:
ser = pd.Series(np.random.randint(1,10,10), pd.date_range('2000-01-01', periods=10, freq='W-SAT'))
# pd.date_range returns a fixed freqency DatetimeIndex

In [59]:
ser

2000-01-01    5
2000-01-08    8
2000-01-15    6
2000-01-22    5
2000-01-29    7
2000-02-05    1
2000-02-12    8
2000-02-19    5
2000-02-26    1
2000-03-04    1
Freq: W-SAT, dtype: int32

15. How to import only specified columns from a csv file?


In [6]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', usecols=['crim', 'medv'])
df.head() # return first n rows (by default, n=5)

crim  medv
0  0.00632  24.0
1  0.02731  21.6
2  0.02729  34.7
3  0.03237  33.4
4  0.06905  36.2

16. How to rename a specific columns in a dataframe?


In [6]:
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df.head()

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small       12.9   15.9       18.8      25.0   
1          NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi       90  Compact       25.9   29.1       32.3      20.0   
3         Audi      100  Midsize        NaN   37.7       44.6      19.0   
4          BMW     535i  Midsize        NaN   30.0        NaN      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                None      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  
3  non-USA       Audi 100  
4  non-USA       BMW 535i  

[5 rows x 27 columns]

In [7]:
df=df.rename(columns = {'Type':'CarType'}) # renaming a column named Type to CarType

In [9]:
df.columns = df.columns.map(lambda x: x.replace('.', '_')) # Replaces . with _ in each column of df
df.head()

Manufacturer    Model  CarType  Min_Price  Price  Max_Price  MPG_city  \
0        Acura  Integra    Small       12.9   15.9       18.8      25.0   
1          NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi       90  Compact       25.9   29.1       32.3      20.0   
3         Audi      100  Midsize        NaN   37.7       44.6      19.0   
4          BMW     535i  Midsize        NaN   30.0        NaN      22.0   

   MPG_highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                None      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn_circle Rear_seat_room  Luggage_room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  
3  non-USA       Audi 100  
4  non-USA       BMW 535i  

[5 rows x 27 columns]

17. How to check if a dataframe has any missing values?


In [4]:
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small       12.9   15.9       18.8      25.0   
1           NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2          Audi       90  Compact       25.9   29.1       32.3      20.0   
3          Audi      100  Midsize        NaN   37.7       44.6      19.0   
4           BMW     535i  Midsize        NaN   30.0        NaN      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van       16.6   19.7       22.7      17.0   
89   Volkswagen   Passat  Compact       17.6   20.0       22.4      21.0   
90   Volkswagen  Corrado   Sporty       22.9   23.3       23.7      18.0   
91        Volvo      240  Compact       21.8   22.7       23.5      21.0   
92          NaN      850  Midsize       24.8   26.7       28.5      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                None      Front  ...        5.0   177.0   
1          25.0  Driver & Passenger      Front  ...        5.0   195.0   
2          26.0         Driver only      Front  ...        5.0   180.0   
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4          30.0                 NaN       Rear  ...        4.0   186.0   
..          ...                 ...        ...  ...        ...     ...   
88         21.0                None      Front  ...        7.0   187.0   
89         30.0                None      Front  ...        5.0   180.0   
90         25.0                None      Front  ...        4.0   159.0   
91         28.0         Driver only       Rear  ...        5.0   190.0   
92         28.0  Driver & Passenger      Front  ...        5.0   184.0   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
1       115.0   71.0         38.0           30.0          15.0  3560.0   
2       102.0   67.0         37.0           28.0          14.0  3375.0   
3       106.0    NaN         37.0           31.0          17.0  3405.0   
4       109.0   69.0         39.0           27.0          13.0  3640.0   
..        ...    ...          ...            ...           ...     ...   
88      115.0   72.0         38.0           34.0           NaN  3960.0   
89      103.0   67.0         35.0           31.5          14.0  2985.0   
90       97.0   66.0         36.0           26.0          15.0  2810.0   
91      104.0   67.0         37.0           29.5          14.0  2985.0   
92      105.0   69.0         38.0           30.0          15.0  3245.0   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88      NaN  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 27 columns]

In [5]:
df.isnull().values.any()


True

18. How to count the number of missing values in each column?


In [7]:
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small       12.9   15.9       18.8      25.0   
1           NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2          Audi       90  Compact       25.9   29.1       32.3      20.0   
3          Audi      100  Midsize        NaN   37.7       44.6      19.0   
4           BMW     535i  Midsize        NaN   30.0        NaN      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van       16.6   19.7       22.7      17.0   
89   Volkswagen   Passat  Compact       17.6   20.0       22.4      21.0   
90   Volkswagen  Corrado   Sporty       22.9   23.3       23.7      18.0   
91        Volvo      240  Compact       21.8   22.7       23.5      21.0   
92          NaN      850  Midsize       24.8   26.7       28.5      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                None      Front  ...        5.0   177.0   
1          25.0  Driver & Passenger      Front  ...        5.0   195.0   
2          26.0         Driver only      Front  ...        5.0   180.0   
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4          30.0                 NaN       Rear  ...        4.0   186.0   
..          ...                 ...        ...  ...        ...     ...   
88         21.0                None      Front  ...        7.0   187.0   
89         30.0                None      Front  ...        5.0   180.0   
90         25.0                None      Front  ...        4.0   159.0   
91         28.0         Driver only       Rear  ...        5.0   190.0   
92         28.0  Driver & Passenger      Front  ...        5.0   184.0   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
1       115.0   71.0         38.0           30.0          15.0  3560.0   
2       102.0   67.0         37.0           28.0          14.0  3375.0   
3       106.0    NaN         37.0           31.0          17.0  3405.0   
4       109.0   69.0         39.0           27.0          13.0  3640.0   
..        ...    ...          ...            ...           ...     ...   
88      115.0   72.0         38.0           34.0           NaN  3960.0   
89      103.0   67.0         35.0           31.5          14.0  2985.0   
90       97.0   66.0         36.0           26.0          15.0  2810.0   
91      104.0   67.0         37.0           29.5          14.0  2985.0   
92      105.0   69.0         38.0           30.0          15.0  3245.0   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88      NaN  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 27 columns]

In [8]:
n_missings_each_col = df.apply(lambda x: x.isnull().sum())
n_missings_each_col.argmax()

23

19. How to replace missing values of multiple numeric columns with the mean?


In [3]:
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
df_out = df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda x: x.fillna(x.mean()))
print(df_out.head())

   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


20. How to use apply function on existing columns with global variables as additional arguments?


In [37]:
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
d = {'Min.Price': np.nanmean, 'Max.Price': np.nanmedian}
df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda x, d: x.fillna(d[x.name](x)), args=(d, ))
df.head()

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small  12.900000   15.9      18.80      25.0   
1          NaN   Legend  Midsize  29.200000   33.9      38.70      18.0   
2         Audi       90  Compact  25.900000   29.1      32.30      20.0   
3         Audi      100  Midsize  17.118605   37.7      44.60      19.0   
4          BMW     535i  Midsize  17.118605   30.0      19.15      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                None      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  
3  non-USA       Audi 100  
4  non-USA       BMW 535i  

[5 rows x 27 columns]

21. How to select a specific column from a dataframe as a dataframe instead of a series?


In [5]:
# Input
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

# Solution
type(df[['a']])
type(df.loc[:, ['a']])
type(df.iloc[:, [0]])

pandas.core.frame.DataFrame

22. How to set the number of rows and columns displayed in the output?


In [40]:
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
pd.set_option('display.max_columns', 10)
pd.set_option('display.max_rows', 10)


23. How to format or suppress scientific notations in a pandas dataframe?

In [7]:
# Input
df = pd.DataFrame(np.random.random(4)**10, columns=['random'])

# Solution 1: Rounding
df.round(4)


random
0  0.0000
1  0.1287
2  0.6626
3  0.0000

24.  How to format all the values in a dataframe as percentages?

In [8]:
# Input
df = pd.DataFrame(np.random.random(4), columns=['random'])

# Solution
out = df.style.format({
    'random': '{0:.2%}'.format,
})

out

25. How to filter every nth row in a dataframe?

In [9]:
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
print(df.iloc[::20, :][['Manufacturer', 'Model', 'Type']])

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


26. How to create a primary key index by combining relevant columns?

In [10]:
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])

# Solution
df[['Manufacturer', 'Model', 'Type']] = df[['Manufacturer', 'Model', 'Type']].fillna('missing')
df.index = df.Manufacturer + '_' + df.Model + '_' + df.Type
print(df.index.is_unique)

True


27. How to get the row number of the nth largest value in a column?

In [11]:
# Input
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))

# Solution
n = 5
df['a'].argsort()[::-1][n]

5

28. How to get the last n rows of a dataframe with row sum > 100?

In [18]:
# Input
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

# Solution
# print row sums
rowsums = df.apply(np.sum, axis=1)

# last two rows with row sum greater than 100
last_two_rows = df.iloc[np.where(rowsums > 100)[0][-2:], :]

rowsums

0      92
1     126
2      96
3      85
4      76
     ... 
10    111
11     83
12     67
13    108
14    113
Length: 15, dtype: int64

29. How to find and cap outliers from a series or dataframe column?

In [19]:
# Input
ser = pd.Series(np.logspace(-2, 2, 30))

# Solution
def cap_outliers(ser, low_perc, high_perc):
    low, high = ser.quantile([low_perc, high_perc])
    print(low_perc, '%ile: ', low, '|', high_perc, '%ile: ', high)
    ser[ser < low] = low
    ser[ser > high] = high
    return(ser)

capped_ser = cap_outliers(ser, .05, .95)

0.05 %ile:  0.016049294076965887 | 0.95 %ile:  63.87667222018393


30. How to reshape a dataframe to the largest possible square after removing the negative values?


In [3]:
# Input
df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10,-1))
print(df)

# Solution
# Step 1: remove negative values from arr
arr = df[df > 0].values.flatten()
arr_qualified = arr[~np.isnan(arr)]

# Step 2: find side-length of largest possible square
n = int(np.floor(arr_qualified.shape[0]**.5))

# Step 3: Take top n^2 items without changing positions
top_indexes = np.argsort(arr_qualified)[::-1]
output = np.take(arr_qualified, sorted(top_indexes[:n**2])).reshape(n, -1)
print(output)

    0   1   2   3   4   5   6   7   8   9
0  18  -9  38 -10  -2  23  33   8  12  38
1  44  -9  32 -18 -18   1  13  -9 -20 -17
2  27  47  -4  35  29  47  -8  43  26  41
3  44  41   6  -8  44  22   3  47  41  47
4   4  45 -10   3  47  27  21  -4  28   1
5   3  -1  33  38   6   2  24  -7  -9  16
6  41  18  -6  45 -13  37  43  16   1  24
7 -14  30   7  -5  24   8 -16  -2  31  31
8 -15  49  26  23  44  45  25 -17  -9  -5
9  42  26   7 -11 -10 -11  36 -15   4  -4
[[18. 38. 23. 33.  8. 12. 38. 44.]
 [32. 13. 27. 47. 35. 29. 47. 43.]
 [26. 41. 44. 41.  6. 44. 22.  3.]
 [47. 41. 47.  4. 45.  3. 47. 27.]
 [21. 28.  3. 33. 38.  6. 24. 16.]
 [41. 18. 45. 37. 43. 16. 24. 30.]
 [ 7. 24.  8. 31. 31. 49. 26. 23.]
 [44. 45. 25. 42. 26.  7. 36.  4.]]


31. How to swap two rows of a dataframe?

In [4]:
# Input
df = pd.DataFrame(np.arange(25).reshape(5, -1))

# Solution
def swap_rows(df, i1, i2):
    a, b = df.iloc[i1, :].copy(), df.iloc[i2, :].copy()
    df.iloc[i1, :], df.iloc[i2, :] = b, a
    return df

print(swap_rows(df, 1, 2))

    0   1   2   3   4
0   0   1   2   3   4
1  10  11  12  13  14
2   5   6   7   8   9
3  15  16  17  18  19
4  20  21  22  23  24


32. How to reverse the rows of a dataframe?

In [5]:
# Input
df = pd.DataFrame(np.arange(25).reshape(5, -1))

# Solution 1
df.iloc[::-1, :]

# Solution 2
print(df.loc[df.index[::-1], :])

    0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4


33. How to create one-hot encodings of a categorical variable (dummy variables)?

In [6]:
# Input
df = pd.DataFrame(np.arange(25).reshape(5,-1), columns=list('abcde'))

# Solution
df_onehot = pd.concat([pd.get_dummies(df['a']), df[list('bcde')]], axis=1)
print(df_onehot)

   0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24


34. Which column contains the highest number of row-wise maximum values?

In [7]:
# Input
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1))

# Solution
print('Column with highest row maxes: ', df.apply(np.argmax, axis=1).value_counts().index[0])

Column with highest row maxes:  1


35. How to create a new column that contains the row number of nearest column by euclidean distance?

In [9]:
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1), columns=list('pqrs'), index=list('abcdefghij'))

# Solution
import numpy as np

# init outputs
nearest_rows = []
nearest_distance = []

# iterate rows.
for i, row in df.iterrows():
    curr = row
    rest = df.drop(i)
    e_dists = {}  # init dict to store euclidean dists for current row.
    # iterate rest of rows for current row
    for j, contestant in rest.iterrows():
        # compute euclidean dist and update e_dists
        e_dists.update({j: round(np.linalg.norm(curr.values - contestant.values))})
    # update nearest row to current row and the distance value
    nearest_rows.append(max(e_dists, key=e_dists.get))
    nearest_distance.append(max(e_dists.values()))

df['nearest_row'] = nearest_rows
df['dist'] = nearest_distance
df

p   q   r   s nearest_row  dist
a  59  67  83  97           e   101
b  41  96  75  13           f   112
c  79  87  67  32           f   117
d  81  17  48  35           f    99
e  73  59  10  29           f   125
f   1  15  89  77           i   137
g  96  84  64  53           f   122
h  97  21  46  62           b   110
i  86  86  16  41           f   137
j  96  40  57  48           f   107

36. How to know the maximum possible correlation value of each column against other columns?

In [10]:
# Input
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1), columns=list('pqrstuvwxy'), index=list('abcdefgh'))
df

# Solution
abs_corrmat = np.abs(df.corr())
max_corr = abs_corrmat.apply(lambda x: sorted(x)[-2])
print('Maximum Correlation possible for each column: ', np.round(max_corr.tolist(), 2))

Maximum Correlation possible for each column:  [0.64 0.58 0.57 0.64 0.52 0.73 0.73 0.47 0.51 0.5 ]


37. How to create a column containing the minimum by maximum of each row?

In [12]:
# Input
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

# Solution 1
min_by_max = df.apply(lambda x: np.min(x)/np.max(x), axis=1)

# Solution 2
min_by_max = np.min(df, axis=1)/np.max(df, axis=1)
df

0   1   2   3   4   5   6   7   8   9
0   7  87  17  61  58  63   6  79  46  27
1   2  58  72  54  33  68  49  54  21  63
2  84  97  43  89  98  38  61   7  54  28
3  10  16  48  23  79   4  58  13  19  80
4  47  95  41  44  92  96  53  88  10  10
5  10  90  53  10  73  26  21  47  97  72
6   3  60  32  25   1  94  57  73  76  81
7  19  39  86   6  22  97   1  11  27  77

38. How to create a column that contains the penultimate value in each row?

In [13]:
# Input
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

# Solution
out = df.apply(lambda x: x.sort_values().unique()[-2], axis=1)
df['penultimate'] = out
print(df)

    0   1   2   3   4   5   6   7   8   9  penultimate
0  37  94  16  30  59   8  44  21  43  62           62
1  38  72  99  58   8  66   2  60  63  99           72
2  90  31   4  30  21  71   5  92   5  89           90
3  85  76  80  14  30  38  34  19  73  81           81
4  88  57  68  93  64  78  82  14  48  75           88
5  32  82  98  51  23  99  74  84  58  46           98
6  34  83  66  94  76  25  48  39  40  74           83
7  50   5  65  34   9  81   2  80  64  54           80


39.  How to normalize all columns in a dataframe?

In [15]:
# Input
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

# Solution Q1
out1 = df.apply(lambda x: ((x - x.mean())/x.std()).round(2))
print('Solution Q1\n',out1)

# Solution Q2
out2 = df.apply(lambda x: ((x.max() - x)/(x.max() - x.min())).round(2))
print('Solution Q2\n', out2)  

Solution Q1
       0     1     2     3     4     5     6     7     8     9
0 -0.25  0.38 -0.84 -0.12 -0.63  0.57  0.99  1.34  0.06 -1.00
1  1.09 -0.80 -0.73 -0.93  0.22  1.09 -0.67  0.76 -0.09  1.20
2  0.46 -0.22  0.24  1.73 -1.70 -1.18  0.52 -1.31  1.58 -0.85
3 -2.17 -0.10  1.06 -0.93  0.50  1.40  1.29 -0.66 -1.10  0.71
4  0.78  1.30  0.63  0.16 -0.92  0.21  0.04  1.03 -1.35 -0.75
5  0.02 -1.62  1.53 -0.76  0.96 -0.25 -1.02  0.23  0.67  1.15
6  0.37 -0.25 -0.84  1.24  1.25 -1.33 -1.56 -0.23 -0.59 -1.05
7 -0.30  1.33 -1.06 -0.39  0.32 -0.51  0.40 -1.15  0.82  0.59
Solution Q2
       0     1     2     3     4     5     6     7     8     9
0  0.41  0.32  0.92  0.69  0.64  0.30  0.10  0.00  0.52  0.98
1  0.00  0.72  0.88  1.00  0.35  0.11  0.69  0.22  0.57  0.00
2  0.19  0.53  0.50  0.00  1.00  0.94  0.27  1.00  0.00  0.91
3  1.00  0.48  0.18  1.00  0.25  0.00  0.00  0.75  0.91  0.22
4  0.10  0.01  0.35  0.59  0.73  0.43  0.44  0.12  1.00  0.86
5  0.33  1.00  0.00  0.94  0.10  0.60  0.81 

40. How to compute the correlation of each row with the suceeding row?

In [16]:
# Input
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

# Solution
[df.iloc[i].corr(df.iloc[i+1]).round(2) for i in range(df.shape[0])[:-1]]

[-0.45, -0.33, 0.05, -0.26, 0.68, 0.14, -0.27]

41. How to replace both the diagonals of dataframe with 0?

In [19]:
# Input
df = pd.DataFrame(np.random.randint(1,100, 100).reshape(10, -1))

# Solution
for i in range(df.shape[0]):
    df.iat[i, i] = 0
    df.iat[df.shape[0]-i-1, i] = 0
df

0   1   2   3   4   5   6   7   8   9
0   0  51  12  27  77  73  32  57  72   0
1  79   0  77  25  54  54  88  54   0  54
2  37  89   0  41   8   6  44   0  79  40
3  32  43   9   0  90  78   0  81  92  90
4  87  61  44  50   0   0  80  74  73  36
5  59  77  19  41   0   0  23  31  86  92
6   1  80  29   0  32  83   0  89   5  92
7  19  69   0  72  86  22  48   0  43  91
8  73   0  39  85  40  13  86  69   0  54
9   0  67  89   5  73  95  51   4  76   0

42. How to get the particular group of a groupby dataframe by key?

In [20]:
# Input
df = pd.DataFrame({'col1': ['apple', 'banana', 'orange'] * 3,
                   'col2': np.random.rand(9),
                   'col3': np.random.randint(0, 15, 9)})

df_grouped = df.groupby(['col1'])

# Solution 1
df_grouped.get_group('apple')

# Solution 2
for i, dff in df_grouped:
    if i == 'apple':
        print(dff)

    col1      col2  col3
0  apple  0.196546    11
3  apple  0.791451     1
6  apple  0.602442    13


43.  How to get the n’th largest value of a column when grouped by another column?

In [21]:
# Input
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'taste': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})

print(df)

# Solution
df_grpd = df['taste'].groupby(df.fruit)
df_grpd.get_group('banana').sort_values().iloc[-2]

    fruit     taste  price
0   apple  0.681091     12
1  banana  0.833887      6
2  orange  0.436398      9
3   apple  0.229674      9
4  banana  0.084167      2
5  orange  0.733016     13
6   apple  0.403577      9
7  banana  0.536313      7
8  orange  0.818142      8


0.5363126336801443

44. How to compute grouped mean on pandas dataframe and keep the grouped column as another column (not index)?

In [22]:
# Input
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})

# Solution
out = df.groupby('fruit', as_index=False)['price'].mean()
print(out)

    fruit     price
0   apple  3.666667
1  banana  9.000000
2  orange  4.000000


45. How to join two dataframes by 2 columns so they have only the common rows?

In [24]:
# Input
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})

# Solution
pd.merge(df1, df2, how='inner', left_on=['fruit', 'weight'], right_on=['pazham', 'kilo'], suffixes=['_left', '_right'])

fruit weight  price_left  pazham  kilo  price_right
0   apple   high          14   apple  high            0
1   apple   high           8   apple  high            0
2   apple   high           9   apple  high            0
3  orange    low           6  orange   low           12
4  orange    low           1  orange   low           12
5  orange    low           0  orange   low           12

46. How to remove rows from a dataframe that are present in another dataframe?

In [25]:
# Input
df1 = pd.DataFrame({'fruit': ['apple', 'orange', 'banana'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.arange(9)})

df2 = pd.DataFrame({'fruit': ['apple', 'orange', 'pine'] * 2,
                    'weight': ['high', 'medium'] * 3,
                    'price': np.arange(6)})


# Solution
print(df1[~df1.isin(df2).all(1)])

    fruit  weight  price
2  banana     low      2
3   apple    high      3
4  orange  medium      4
5  banana     low      5
6   apple    high      6
7  orange  medium      7
8  banana     low      8


47. How to get the positions where values of two columns match?

In [35]:
# Input
df = pd.DataFrame({'fruit1': np.random.choice(['apple', 'orange', 'banana'], 10),
                    'fruit2': np.random.choice(['apple', 'orange', 'banana'], 10)})

# Solution
np.where(df.fruit1 == df.fruit2)

(array([5, 7, 8], dtype=int64),)

48. How to create lags and leads of a column in a dataframe?

In [27]:
# Input
df = pd.DataFrame(np.random.randint(1, 100, 20).reshape(-1, 4), columns = list('abcd'))

# Solution
df['a_lag1'] = df['a'].shift(1)
df['b_lead1'] = df['b'].shift(-1)
print(df)

    a   b   c   d  a_lag1  b_lead1
0  78  44  53  25     NaN     35.0
1  13  35  93  66    78.0     30.0
2  91  30  32  32    13.0     95.0
3  11  95  88  75    91.0     91.0
4  74  91  34  24    11.0      NaN


49. How to get the frequency of unique values in the entire dataframe?

In [28]:
# Input
df = pd.DataFrame(np.random.randint(1, 10, 20).reshape(-1, 4), columns = list('abcd'))

# Solution
pd.value_counts(df.values.ravel())

5    6
6    3
3    3
9    2
8    2
4    2
1    1
2    1
dtype: int64

50. How to split a text column into two separate columns?

In [32]:
# Input
df = pd.DataFrame(["STD, City    State",
"33, Kolkata    West Bengal",
"44, Chennai    Tamil Nadu",
"40, Hyderabad    Telengana",
"80, Bangalore    Karnataka"], columns=['row'])

# Solution
df_out = df.row.str.split(',|\t', expand=True)

# Make first row as header
new_header = df_out.iloc[0]
df_out = df_out[1:]
df_out.columns = new_header
print(df_out)

0 STD            City    State
1  33   Kolkata    West Bengal
2  44    Chennai    Tamil Nadu
3  40   Hyderabad    Telengana
4  80   Bangalore    Karnataka
